GET http://localhost:8080/api/hello

###
// @no-log
POST http://localhost:8080/api/purposes/
Content-Type: application/json

{
  "text": "I agree to the processing of my data in accordance to article 6a for the purpose of marketing and tax declaration.",
  "viability": {
    "subjectType": "USER",
    "targetCharacteristic": {
      "type": "USER",
      "characteristic": "DEFAULT"
    }
  }
}

> {%
client.global.set("purposeId", response.body.id);
client.log("purposeId: "+client.global.get("purposeId"))
 %}

###
POST http://localhost:8080/api/purposes/{{purposeId}}/release
Content-Type: application/json

{
  "purposeVersion": {
    "value": 1
  }
}

###
// @no-log
POST http://localhost:8080/api/consents
Content-Type: application/json
X-User-Id: c0c0a000-0000-4000-a000-000000000000

{
  "referencedPurpose": {
    "purposeId": "{{purposeId}}",
    "agreedVersion": {
      "value": 1
    }
  },
  "subjectReference": {
    "id": "c0c0a000-0000-4000-a000-000000000000"
  }
}

###
//@no-log
PATCH http://localhost:8080/api/purposes/{{purposeId}}
Content-Type: application/json

{
  "text": "I agree to the processing of my data in accordance to article 6a for the purpose of tax declaration."
}
